version: '3'
services:
  teleport:
    image: public.ecr.aws/gravitational/teleport:12
    container_name: teleport
    restart: unless-stopped
    entrypoint: /bin/sh
    hostname: tp.example.com
    command: -c "sleep 1 && /usr/bin/dumb-init teleport start -c /etc/teleport/teleport.yaml"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2048M
    ports:
      - "3023:3023"
      - "3024:3024"
      - "3025:3025"
      - "3080:3080"
    volumes:
      - ./teleport/config:/etc/teleport
      - ./teleport/data:/var/lib/teleport
